version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NEO4J_URI=${NEO4J_URI-neo4j://database:7687}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD-password}
      - NEO4J_USERNAME=${NEO4J_USERNAME-neo4j}
      - OPENAI_API_KEY=${OPENAI_API_KEY-}
      - DIFFBOT_API_KEY=${DIFFBOT_API_KEY-}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL-all-MiniLM-L6-v2}
      - LANGCHAIN_ENDPOINT=${LANGCHAIN_ENDPOINT-}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2-}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT-}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY-}
      - IS_EMBEDDING=${IS_EMBEDDING-true}
      - LLM_MODEL_CONFIG_ollama_llama3=${LLM_MODEL_CONFIG_ollama_llama3-}
    env_file:
      - ./.beenv
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - net
    depends_on:
      - neo4j

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    environment:
      - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID-}
      - VITE_BLOOM_URL=${VITE_BLOOM_URL-https://workspace-preview.neo4j.io/workspace/explore?connectURL={CONNECT_URL}&search=Show+me+a+graph&featureGenAISuggestions=true&featureGenAISuggestionsInternal=true}
      - VITE_TIME_PER_PAGE=${VITE_TIME_PER_PAGE-50}
      - VITE_CHUNK_SIZE=${VITE_CHUNK_SIZE-5242880}
      - VITE_LARGE_FILE_SIZE=${VITE_LARGE_FILE_SIZE-5242880}
      - VITE_ENV=${VITE_ENV-DEV}
      - VITE_CHAT_MODES=${VITE_CHAT_MODES-}
      - VITE_BATCH_SIZE=${VITE_BATCH_SIZE-2}
      - VITE_LLM_MODELS=${VITE_LLM_MODELS-}
      - VITE_LLM_MODELS_PROD=${VITE_LLM_MODELS_PROD-openai_gpt_4o,openai_gpt_4o_mini,diffbot,gemini_1.5_flash}
      - DEPLOYMENT_ENV=local
    env_file:
      - ./.feenv
    container_name: frontend
    ports:
      - "8080:8080"
    networks:
      - net 

  neo4j:
    image: docker.io/neo4j:5.26.0-community-ubi9
    volumes:
      - ./neo4j/logs:/logs
      - ./neo4j/config:/var/lib/neo4j/conf
      - ./neo4j/data:/data
      - ./neo4j/plugins:/plugins
      - ./neo4j/import:/var/lib/neo4j/import
    env_file:
      - ./.neo4jenv
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
    container_name: neo4j
    networks:
      - net

networks:
  net:
